# This file defines all the backend services for our project.
services:

  # Service 1: The MQTT Broker (our message post office)
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # Service 2: The LangChain AI Service (the brain)
  llm_service:
    build: ./llm_service
    container_name: llm_service
    restart: unless-stopped
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      PYTHONUNBUFFERED: 1
    depends_on:
      - mosquitto

  # Service 3: The NEW Data Logger Service (the ears)
  data_logger_service:
    build: ./data_logger
    container_name: data_logger_service
    restart: unless-stopped
    environment:
      # needs access to Supabase
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      PYTHONUNBUFFERED: 1
    depends_on:
      - mosquitto