# In data_logger/Dockerfile

FROM python:3.9-slim

WORKDIR /app

# We need the same libraries (paho-mqtt and supabase)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the logger script
COPY data_logger.py .

# Run the logger script when the container starts
CMD ["python", "data_logger.py"]